export {
  defineCli,
  helpCapability,
  outputCapability,
  type CliContract,
  type CliContractDependencies,
  type CliContractRawInput,
  type CliContractResult,
  type CliContractRoot,
  type CliGrammar,
  type CliManifest,
  type CanonicalLongOption,
  type CompletionFact,
  type CompletionHandlerContext,
  type CompletionOutcome,
  type CompletionRootCliDefinition,
  type CompletionRootCommandDefinition,
  type ContractTypeError,
  type DataFact,
  type DataFactUnion,
  type DataHandlerContext,
  type DataOutcome,
  type DataRootCliDefinition,
  type DataRootCommandDefinition,
  type DataVariantDefinition,
  type DataVariantDefinitions,
  type DefineCli,
  type HelpCapability,
  type OutcomeFact,
  type OutputCapability,
  type RawValueOptionInput,
  type RawValueOptionInputForSchema,
  type RootCliDefinition,
  type RootCommandDefinition,
  type RootCommandGrammar,
  type RootCommandManifest,
  type SchemaManifest,
  type ValueOptionDefinition,
  type ValueOptionDefinitions,
  type ValueOptionDefinitionsForInput,
  type ValueOptionGrammar,
} from "#/cli-contract";
export {
  executeCli,
  type CliOutput,
  type CliOutputDestination,
  type CliTermination,
  type ExecuteCliOptions,
  type WriteCliOutput,
} from "#/cli-execution";
export {
  parseCliInvocation,
  type CliInvocation,
  type CommandUsage,
  type HelpRequest,
  type InputRejectedIssue,
  type NonEmptyUsageIssues,
  type ParsedInvocation,
  type SchemaIssueEvidence,
  type UnexpectedPositionalIssue,
  type UsageIssue,
  type UsageFailure,
} from "#/cli-invocation";
export {
  ContractDefinitionError,
  type ContractDefinitionIssue,
  type SchemaDefinitionTarget,
} from "#/contract-definition-error";
export type {
  ContractSchema,
  ContractSchemaInput,
  ContractSchemaOutput,
  EmptyCliInput,
  JsonObject,
  JsonPrimitive,
  JsonValue,
} from "#/contract-schema";
