export {
  defineCli,
  helpCapability,
  outputCapability,
  versionCapability,
  type CliContract,
  type CliContractDependencies,
  type CliContractRawInput,
  type CliContractResult,
  type CliContractRoot,
  type CliGrammar,
  type CliManifest,
  type CommandGrammar,
  type CommandGroupDefinition,
  type CommandGroupGrammar,
  type CommandGroupManifest,
  type CommandWireManifest,
  type CanonicalLongOption,
  type CompletionFact,
  type CompletionHandlerContext,
  type CompletionOutcome,
  type CompletionRootCliDefinition,
  type CompletionRootCommandDefinition,
  type ContractTypeError,
  type DataFact,
  type DataFactUnion,
  type DataHandlerContext,
  type DataOutcome,
  type DataRootCliDefinition,
  type DataRootCommandDefinition,
  type DataVariantDefinition,
  type DataVariantDefinitions,
  type StreamHandlerContext,
  type StreamOutcome,
  type StreamRecordDefinition,
  type StreamRecordDefinitions,
  type StreamRecordFact,
  type StreamRecordFactUnion,
  type StreamRootCliDefinition,
  type StreamRootCommandDefinition,
  type StreamSuccessFact,
  type DefineCli,
  type DefineCommand,
  type FailureFact,
  type FailureFactUnion,
  type FailureOutcome,
  type FailureVariantDefinition,
  type FailureVariantDefinitions,
  type FailureVariantManifest,
  type FieldDefinition,
  type FieldDefinitions,
  type FieldDefinitionsForInput,
  type FieldGrammar,
  type ForbiddenCombinationUsageConstraint,
  type ForbiddenCombinationValue,
  type FlagDefinition,
  type FlagGrammar,
  type HelpCapability,
  type HelpCapabilityDefinition,
  type HierarchyCliGrammar,
  type HierarchyCliManifest,
  type OutcomeFact,
  type OutputCapability,
  type OutputFormat,
  text,
  type SilentText,
  type TextLine,
  type TextLines,
  type PositionalDefinition,
  type PositionalGrammar,
  type RepeatableOptionDefinition,
  type RepeatableOptionGrammar,
  type RequiresUsageConstraint,
  type RawFieldInput,
  type RawValueOptionInput,
  type RawValueOptionInputForSchema,
  type RootCliDefinition,
  type RootGroupDefinition,
  type RootGroupGrammar,
  type RootCommandDefinition,
  type RootCommandGrammar,
  type RootCommandManifest,
  type ExecutableCommandDefinition,
  type ExecutableCommandGrammar,
  type ExecutableCommandManifest,
  type ShortOptionAlias,
  type SchemaManifest,
  type SharedOptionDefinition,
  type SharedOptionDefinitions,
  type ValueOptionDefinition,
  type ValueOptionDefinitions,
  type ValueOptionDefinitionsForInput,
  type ValueOptionGrammar,
  type VersionCapability,
  type VersionCapabilityDefinition,
  type VariadicPositionalDefinition,
  type VariadicPositionalGrammar,
  type UsageConstraint,
  type UsageConstraintGrammar,
  type ExclusiveUsageConstraint,
} from "#/cli-contract";
export {
  executeCli,
  type CliOutput,
  type CliOutputDestination,
  type CliTermination,
  type ExecuteCliOptions,
  type WriteCliOutput,
} from "#/cli-execution";
export { CliWriteError } from "#/cli-write-error";
export {
  parseCliInvocation,
  type CliInvocation,
  type CommandUsage,
  type ConflictingFlagIssue,
  type ConflictingOutputFormatIssue,
  type ExclusiveUsageConstraintIssue,
  type ForbiddenUsageCombinationIssue,
  type HelpRequest,
  type InputRejectedIssue,
  type InvalidOutputFormatIssue,
  type MissingOptionValueIssue,
  type MissingRequiredFieldIssue,
  type NonEmptyUsageIssues,
  type OptionOccurrenceEvidence,
  type ParsedInvocation,
  type RepeatedOptionIssue,
  type RequiredByUsageConstraintIssue,
  type SchemaIssueEvidence,
  type UnexpectedPositionalIssue,
  type UnexpectedOptionValueIssue,
  type UnknownOptionIssue,
  type UnknownCommandIssue,
  type UsageIssue,
  type UsageFailure,
  type VersionRequest,
} from "#/cli-invocation";
export {
  ContractExecutionError,
  type ContractExecutionIssue,
} from "#/contract-execution-error";
export {
  ContractDefinitionError,
  type ContractDefinitionIssue,
  type SchemaDefinitionTarget,
} from "#/contract-definition-error";
export type {
  ContractSchema,
  ContractSchemaInput,
  ContractSchemaOutput,
  EmptyCliInput,
  JsonObject,
  JsonPrimitive,
  JsonValue,
} from "#/contract-schema";
